networks:
  docker-mirror:

services:
  reverse-proxy-server:
    image: haproxy:2.9-alpine
    container_name: reverse-proxy-docker-mirror
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    ports:
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/etc/ssl/private:ro
    logging:
      driver: json-file
      options:
        max-size: "2048k"
        max-file: "10"
    networks:
      - docker-mirror

  docker-registry-mirror:
    image: registry:2
    container_name: docker-registry-mirror
    environment:
      REGISTRY_PROXY_REMOTEURL: "https://registry-1.docker.io"
    volumes:
      - ./certs:/certs:ro
      - ./config.yml:/etc/docker/registry/config.yml
      - ./registry-cache:/var/lib/registry
    networks:
      - docker-mirror
    logging:
      driver: json-file
      options:
        max-size: "2048k"
        max-file: "10"