version: 0.1
log:
  fields:
    service: registry
    environment: production

http:
  addr: :443
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/dockerio.ru/fullchain.pem
    key: /certs/dockerio.ru/privkey.pem

storage:
  filesystem:
    rootdirectory: /var/lib/registry
  cache:
    blobdescriptor: inmemory

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3